// Pure generators for the search-engine pages built at deploy time (see build-pages.mjs):
// one static page per painting, the home index of paintings, sitemap.xml and llms.txt.
// No filesystem or network here, so everything is unit tested in tests/pages.test.mjs.

export const SITE = "https://brancan.github.io/tangle-machine/";
export const OG_IMAGE = `${SITE}og-image.png`;
export const INDEX_START = "<!-- paintings-index:start -->";
export const INDEX_END = "<!-- paintings-index:end -->";

const TRADEMARK =
  "Zentangle® is a registered trademark of Zentangle, Inc. This is an independent project, not " +
  "created, endorsed or licensed by Zentangle, Inc.; many pieces are inspired by the Zentangle® " +
  "Method of pattern drawing, and tangle names belong to their creators.";

export function escapeHtml(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeXml(text) {
  return escapeHtml(text).replace(/&#39;/g, "&apos;");
}

export function paintingUrl(painting) {
  return `${SITE}p/${painting.id}.html`;
}

// Collapses whitespace and trims to `max` characters at a word boundary, with an ellipsis.
export function metaDescription(text, max = 155) {
  const clean = String(text || "").replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const space = cut.lastIndexOf(" ");
  return `${(space > max / 2 ? cut.slice(0, space) : cut).replace(/[\s,;:.–—-]+$/, "")}…`;
}

// "After Georg Nees's Schotter (1968): an interpretation…" → "Georg Nees's Schotter (1968)".
export function homageOf(painting) {
  const match = String(painting.description || "").match(/^After ([^:]+):/);
  return match ? match[1].trim() : null;
}

// JSON for a <script> element: `<` escaped so no text can close the element.
function jsonForScript(data) {
  return JSON.stringify(data, null, 2).replace(/</g, "\\u003c");
}

// Generated SVG is trusted, but strip scripts and inline handlers anyway.
function cleanSvg(svg) {
  return String(svg)
    .replace(/<script[\s\S]*?<\/script\s*>/gi, "")
    .replace(/<script[^>]*\/>/gi, "")
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*')/gi, "");
}

function instructionHtml(parts) {
  return parts
    .map(({ text, param, choice }) =>
      param ? `<span class="blank${choice ? " choice" : ""}">${escapeHtml(text)}</span>` : escapeHtml(text)
    )
    .join("");
}

function artworkLd(painting) {
  const homage = homageOf(painting);
  const data = {
    "@context": "https://schema.org",
    "@type": "VisualArtwork",
    name: painting.title,
    description: painting.description,
    url: paintingUrl(painting),
    image: OG_IMAGE,
    inLanguage: "en",
    artform: "Generative drawing",
    artMedium: "SVG generated by code",
    creator: { "@type": "Organization", name: "Tangle Machine", url: SITE },
    keywords: (painting.tags || []).join(", "),
    isPartOf: { "@type": "WebSite", name: "Tangle Machine", url: SITE },
  };
  if (homage) data.citation = homage;
  return data;
}

const PAGE_STYLE = `
      .painting-page { max-width: 72ch; margin: 0 auto; }
      .painting-page h1 { margin: 0.5rem 0 0.5rem; font-family: var(--serif); font-weight: 500; font-size: 2.4rem; }
      .painting-page .lede { margin: 0; font-family: var(--serif); font-size: 1.15rem; }
      .painting-page .art { margin: 1.5rem 0; }
      .painting-page .art svg { display: block; width: 100%; height: auto; }
      .painting-page .actions { display: flex; flex-wrap: wrap; gap: 0.5rem 1.5rem; align-items: baseline; }
      .painting-page .open { font-weight: 600; }
      .painting-page .pager { display: flex; justify-content: space-between; gap: 1rem; margin: 2rem 0 1rem; }
      .painting-page .credits { color: var(--muted); font-size: 0.85rem; }`;

// The full HTML of /p/<id>.html. `instruction` is the output of Instruction.render with the
// painting's default values; `svg` is Gallery.render of the default values.
export function paintingPage(painting, { svg, instruction = [], number, prev, next }) {
  const url = paintingUrl(painting);
  const title = `${painting.title} · Tangle Machine`;
  const description = metaDescription(painting.description);
  const t = escapeHtml(title);
  const d = escapeHtml(description);
  const alt = escapeHtml(`${painting.title}, a drawing made with code`);
  const tags = (painting.tags || []).map((tag) => `<span>${escapeHtml(tag)}</span>`).join("");
  const label = number ? `Instruction #${number}` : "Instruction";
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${t}</title>
    <meta name="description" content="${d}" />
    <link rel="canonical" href="${url}" />
    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="Tangle Machine" />
    <meta property="og:title" content="${t}" />
    <meta property="og:description" content="${d}" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="${OG_IMAGE}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${t}" />
    <meta name="twitter:description" content="${d}" />
    <meta name="twitter:image" content="${OG_IMAGE}" />
    <link rel="icon" href="../favicon.svg" type="image/svg+xml" />
    <link rel="stylesheet" href="../styles.css" />
    <style>${PAGE_STYLE}
    </style>
    <script type="application/ld+json">
${jsonForScript(artworkLd(painting))}
    </script>
    <script data-goatcounter="https://tanglemachine.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
  </head>
  <body>
    <header class="site-header">
      <a class="brand" href="../index.html">Tangle Machine</a>
      <span class="tagline">Drawings made with code</span>
      <a href="../showcase.html" style="margin-left: auto">Gallery</a>
      <a href="../about.html">About</a>
    </header>

    <main>
      <article class="painting-page">
        <h1>${escapeHtml(painting.title)}</h1>
        <p class="lede">${escapeHtml(painting.description)}</p>
        <section class="instruction" aria-label="Instruction">
          <span class="instruction-label">${label}</span>
          ${instructionHtml(instruction)}
        </section>
        <figure class="art frame" role="img" aria-label="${alt}">
          ${cleanSvg(svg)}
        </figure>
        <div class="actions">
          <a class="open" href="../index.html#/${encodeURIComponent(painting.id)}">Open in studio →</a>
          <span class="card-tags">${tags}</span>
        </div>
        <p class="hint">Change its variables, watch it being drawn, or rewrite its code in the studio.</p>
        <nav class="pager" aria-label="More paintings">
          <a href="${encodeURIComponent(prev.id)}.html" rel="prev">← ${escapeHtml(prev.title)}</a>
          <a href="${encodeURIComponent(next.id)}.html" rel="next">${escapeHtml(next.title)} →</a>
        </nav>
        <p class="credits">
          ${TRADEMARK} Source code on
          <a href="https://github.com/brancan/tangle-machine">GitHub</a>.
        </p>
      </article>
    </main>
  </body>
</html>
`;
}

// Static, crawlable list of every painting for the home page.
export function homeIndex(paintings) {
  const items = paintings
    .map((p) => `      <li><a href="p/${encodeURIComponent(p.id)}.html">${escapeHtml(p.title)}</a></li>`)
    .join("\n");
  return (
    `<nav class="painting-index" aria-label="All paintings">\n` +
    `  <h2>All paintings</h2>\n` +
    `  <ul>\n${items}\n  </ul>\n` +
    `</nav>`
  );
}

// Replaces whatever sits between the two markers (kept) with `snippet`.
export function injectBetween(html, startMarker, endMarker, snippet) {
  const start = html.indexOf(startMarker);
  const end = html.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`missing or misplaced marker ${start === -1 ? startMarker : endMarker}`);
  }
  return html.slice(0, start + startMarker.length) + `\n${snippet}\n` + html.slice(end);
}

// urls: [{ loc, lastmod: "YYYY-MM-DD" }]
export function sitemap(urls) {
  const entries = urls.map(({ loc, lastmod }) => {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(lastmod || "")) throw new Error(`invalid lastmod "${lastmod}" for ${loc}`);
    return `  <url>\n    <loc>${escapeXml(loc)}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
  });
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${entries.join("\n")}\n` +
    `</urlset>\n`
  );
}

function oneLine(text) {
  return String(text || "").replace(/\s+/g, " ").trim();
}

// https://llmstxt.org: H1, blockquote summary, then sections of links.
export function llmsTxt(paintings) {
  const lines = [
    "# Tangle Machine",
    "",
    "> An interactive gallery of drawings made with code. Each painting is a small JavaScript " +
      "function and a written instruction, after Sol LeWitt: visitors change its variables, " +
      "watch it being drawn, and read or rewrite its code in the browser.",
    "",
    "Many pieces are inspired by the Zentangle® Method of pattern drawing; others are homages to " +
      "pioneers of computer and op art. Zentangle® is a registered trademark of Zentangle, Inc.; " +
      "this is an independent project.",
    "",
    "## Pages",
    "",
    `- [Gallery of paintings](${SITE}): every painting, with a studio to play with each one`,
    `- [About](${SITE}about.html): why each drawing is treated as an instruction, after Sol LeWitt`,
    `- [Visitor gallery](${SITE}showcase.html): variants published by visitors`,
    "",
    "## Paintings",
    "",
    ...paintings.map((p) => `- [${oneLine(p.title)}](${paintingUrl(p)}): ${metaDescription(p.description, 200)}`),
    "",
  ];
  return lines.join("\n");
}
